"""empty message

Revision ID: 2a235eb031ae
Revises: cde34079f1f0
Create Date: 2020-02-01 14:02:34.019937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a235eb031ae'
down_revision = 'cde34079f1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('size', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
