"""empty message

Revision ID: 770a2aa760e8
Revises: 2a235eb031ae
Create Date: 2020-02-01 18:27:13.520257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770a2aa760e8'
down_revision = '2a235eb031ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('size', sa.String(length=120), nullable=True))
    op.alter_column('Venue', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('Venue', 'size')
    # ### end Alembic commands ###
