"""empty message

Revision ID: c0de0819f9f0
Revises: c3880377ac48
Create Date: 2020-02-04 15:45:02.049082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0de0819f9f0'
down_revision = 'c3880377ac48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'type')
    op.drop_column('Shows', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('type', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('type', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
