"""empty message

Revision ID: c3880377ac48
Revises: 8dc5999a5c74
Create Date: 2020-02-04 15:44:28.982771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3880377ac48'
down_revision = '8dc5999a5c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('type', sa.String(length=120), nullable=True))
    op.add_column('Shows', sa.Column('type', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'type')
    op.drop_column('Artist', 'type')
    # ### end Alembic commands ###
