"""empty message

Revision ID: cde34079f1f0
Revises: c9916b6ae2bd
Create Date: 2020-02-01 13:57:55.112214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde34079f1f0'
down_revision = 'c9916b6ae2bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('size', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'size')
    # ### end Alembic commands ###
